name: ci

on:
  push:

jobs:
  docker:
    env:
      DOCKER_BUILD_RECORD_UPLOAD: false
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and export
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: api_base/test:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
          outputs: type=docker,dest=/tmp/api_base_test_image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api base test image
          path: /tmp/api_base_test_image.tar

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache
  use:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api base test image
          path: /tmp

      - name: Load image
        run: |
          docker load --input /tmp/api_base_test_image.tar
          docker image ls -a
      - name: Run container
        run: docker run -p 3000:3000 api_base/test:latest echo "Hello, world!"
